sudo: false

language: python

python:
  - 3.7
  - 3.6
  - 3.5

env:
  - TOX_ENV=django3
  - TOX_ENV=django22
  - TOX_ENV=django21
  - TOX_ENV=django20
  - TOX_ENV=django111

matrix:
  exclude:
    - python: 3.5
      env: TOX_ENV=django3

before_install:
  - "pip install -U pip"

install:
  - pip install tox

script:
  - tox -e $TOX_ENV
